CREATE TABLE `pamirs_schedule_queue` (
  `ID` bigint(20) NOT NULL,
  `TASK_TYPE` varchar(50) NOT NULL,
  `QUEUE_ID` varchar(50) NOT NULL,
  `CUR_SERVER` varchar(100) DEFAULT NULL,
  `REQ_SERVER` varchar(100) DEFAULT NULL,
  `OWN_SIGN` varchar(50) NOT NULL,
  `BASE_TASK_TYPE` varchar(50) DEFAULT NULL,
  `GMT_CREATE` datetime NOT NULL,
  `GMT_MODIFIED` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IND_PAMIRS_SCHEDULE_QUEUEID` (`TASK_TYPE`,`QUEUE_ID`,`OWN_SIGN`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `pamirs_schedule_server` (
  `ID` bigint(20) NOT NULL,
  `UUID` varchar(100) NOT NULL,
  `TASK_TYPE` varchar(50) NOT NULL,
  `IP` varchar(50) NOT NULL,
  `HOST_NAME` varchar(50) NOT NULL,
  `MANAGER_PORT` bigint(10) NOT NULL,
  `THREAD_NUM` bigint(5) NOT NULL,
  `REGISTER_TIME` datetime NOT NULL,
  `HEARTBEAT_TIME` datetime NOT NULL,
  `LAST_FETCH_DATA_TIME` datetime DEFAULT NULL,
  `VERSION` bigint(12) NOT NULL,
  `JMX_URL` varchar(200) DEFAULT NULL,
  `DEALINFO_DESC` varchar(1000) DEFAULT NULL,
  `NEXT_RUN_START_TIME` varchar(100) DEFAULT NULL,
  `NEXT_RUN_END_TIME` varchar(100) DEFAULT NULL,
  `OWN_SIGN` varchar(50) DEFAULT NULL,
  `BASE_TASK_TYPE` varchar(50) DEFAULT NULL,
  `GMT_CREATE` datetime NOT NULL,
  `GMT_MODIFIED` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IND_PAMIRS_SCHEDULE_UUID` (`UUID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `pamirs_schedule_server_his` (
  `ID` bigint(20) NOT NULL,
  `UUID` varchar(100) NOT NULL,
  `TASK_TYPE` varchar(50) NOT NULL,
  `IP` varchar(50) NOT NULL,
  `HOST_NAME` varchar(50) NOT NULL,
  `MANAGER_PORT` bigint(10) NOT NULL,
  `THREAD_NUM` bigint(5) NOT NULL,
  `REGISTER_TIME` datetime NOT NULL,
  `HEARTBEAT_TIME` datetime NOT NULL,
  `VERSION` bigint(12) NOT NULL,
  `JMX_URL` varchar(200) DEFAULT NULL,
  `DEALINFO_DESC` varchar(1000) DEFAULT NULL,
  `NEXT_RUN_START_TIME` varchar(100) DEFAULT NULL,
  `NEXT_RUN_END_TIME` varchar(100) DEFAULT NULL,
  `OWN_SIGN` varchar(50) DEFAULT NULL,
  `BASE_TASK_TYPE` varchar(50) DEFAULT NULL,
  `GMT_CREATE` datetime NOT NULL,
  `GMT_MODIFIED` datetime NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `pamirs_schedule_tasktrun` (
  `ID` bigint(20) NOT NULL,
  `TASK_TYPE` varchar(100) NOT NULL,
  `OWN_SIGN` varchar(50) DEFAULT NULL,
  `BASE_TASK_TYPE` varchar(50) DEFAULT NULL,
  `LAST_ASSIGN_TIME` datetime DEFAULT NULL,
  `LAST_ASSIGN_UUID` varchar(100) DEFAULT NULL,
  `GMT_CREATE` datetime NOT NULL,
  `GMT_MODIFIED` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IND_PAMIRS_SCHEDULE_RUN_TASK` (`TASK_TYPE`,`OWN_SIGN`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `pamirs_schedule_tasktype` (
  `ID` bigint(20) NOT NULL,
  `TASK_TYPE` varchar(100) NOT NULL,
  `LAST_ASSIGN_TIME` datetime DEFAULT NULL,
  `LAST_ASSIGN_UUID` varchar(100) DEFAULT NULL,
  `HEARTBEAT_RATE` bigint(10) DEFAULT NULL,
  `JUDGE_DEAD_INTERVAL` bigint(10) DEFAULT NULL,
  `THREAD_NUMBER` bigint(5) DEFAULT NULL,
  `EXECUTE_NUMBER` int(11) DEFAULT NULL,
  `FETCH_NUMBER` int(11) DEFAULT NULL,
  `SLEEP_TIME_NODATA` float(10,3) DEFAULT NULL,
  `SLEEP_TIME_INTERVAL` float(10,3) DEFAULT NULL,
  `PROCESSOR_TYPE` varchar(20) DEFAULT NULL,
  `PERMIT_RUN_START_TIME` varchar(100) DEFAULT NULL,
  `PERMIT_RUN_END_TIME` varchar(100) DEFAULT NULL,
  `DEAL_BEAN_NAME` varchar(100) NOT NULL,
  `EXPIRE_OWN_SIGN_INTERVAL` float(10,2) DEFAULT NULL,
  `GMT_CREATE` datetime NOT NULL,
  `GMT_MODIFIED` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IND_PAMIRS_TASKTYPE_TASKTYPE` (`TASK_TYPE`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

